openapi: 3.0.0
info:
  title: Repo2Graph API
  description: API for querying code repository graph data
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /nodes:
    get:
      summary: /nodes
      description: Get nodes of a specific type
      parameters:
        - name: node_type
          in: query
          description: Type of node to retrieve
          required: true
          schema:
            type: string
            enum: [Page, Function, Class, Trait, Datamodel, Request, Endpoint, Test, E2etest]
        - name: concise
          in: query
          description: Only include name and file in returned data
          required: false
          schema:
            type: boolean
            default: false
        - name: ref_ids
          in: query
          description: Comma-separated list of reference IDs
          required: false
          schema:
            type: string
        - name: output
          in: query
          description: Output format
          required: false
          schema:
            type: string
            enum: [json, snippet]
            default: json
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
  /search:
    get:
      summary: /search
      description: Search for nodes matching a query
      parameters:
        - name: query
          in: query
          description: Search query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of results to return
          required: false
          schema:
            type: integer
            default: 25
        - name: concise
          in: query
          description: Only include name and file in returned data
          required: false
          schema:
            type: boolean
            default: false
        - name: node_types
          in: query
          description: Comma-separated list of node types to search
          required: false
          schema:
            type: string
        - name: node_type
          in: query
          description: Single node type to search
          required: false
          schema:
            type: string
            enum: [Page, Function, Class, Trait, Datamodel, Request, Endpoint, Test, E2etest]
        - name: method
          in: query
          description: Search method to use
          required: false
          schema:
            type: string
        - name: output
          in: query
          description: Output format
          required: false
          schema:
            type: string
            enum: [json, snippet]
            default: json
        - name: tests
          in: query
          description: Include test nodes in results
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
  /map:
    get:
      summary: /map
      description: Get a visual map of node relationships
      parameters:
        - name: node_type
          in: query
          description: Type of the starting node
          required: false
          schema:
            type: string
            enum: [Page, Function, Class, Trait, Datamodel, Request, Endpoint, Test, E2etest]
        - name: name
          in: query
          description: Name of the starting node
          required: false
          schema:
            type: string
            example: LeaderboardPage, TicketPage
        - name: ref_id
          in: query
          description: Reference ID of the starting node
          required: false
          schema:
            type: string
        - name: tests
          in: query
          description: Include test nodes in the map
          required: false
          schema:
            type: boolean
            default: true
        - name: depth
          in: query
          description: Maximum depth of relationships to traverse
          required: false
          schema:
            type: integer
            default: 7
        - name: direction
          in: query
          description: Direction of relationships to traverse
          required: false
          schema:
            type: string
            enum: [incoming, outgoing, both]
            default: both
        - name: trim
          in: query
          description: Comma-separated list of node types to trim from the map
          required: false
          schema:
            type: string
      responses:
        '200':
          description: HTML visualization of the map
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
  /repo_map:
    get:
      summary: /repo_map
      description: Get a visual map of a repository
      parameters:
        - name: name
          in: query
          description: Name of the repository
          required: false
          schema:
            type: string
        - name: ref_id
          in: query
          description: Reference ID of the repository
          required: false
          schema:
            type: string
      responses:
        '200':
          description: HTML visualization of the repository map
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
  /code:
    get:
      summary: /code
      description: Get code for a node and its relationships
      parameters:
        - name: node_type
          in: query
          description: Type of the node
          required: false
          schema:
            type: string
            enum: [Page, Function, Class, Trait, Datamodel, Request, Endpoint, Test, E2etest]
        - name: name
          in: query
          description: Name of the node
          required: false
          schema:
            type: string
            example: LeaderboardPage, TicketPage
        - name: ref_id
          in: query
          description: Reference ID of the node
          required: false
          schema:
            type: string
        - name: tests
          in: query
          description: Include test code
          required: false
          schema:
            type: boolean
            default: true
        - name: depth
          in: query
          description: Maximum depth of relationships to traverse
          required: false
          schema:
            type: integer
            default: 7
        - name: direction
          in: query
          description: Direction of relationships to traverse
          required: false
          schema:
            type: string
            enum: [incoming, outgoing, both]
            default: both
        - name: trim
          in: query
          description: Comma-separated list of node types to trim
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Code text
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal Server Error
  /shortest_path:
    get:
      summary: /shortest_path
      description: Find the shortest path between two nodes
      parameters:
        - name: start_node_key
          in: query
          description: Key of the starting node
          required: false
          schema:
            type: string
        - name: end_node_key
          in: query
          description: Key of the ending node
          required: false
          schema:
            type: string
        - name: start_ref_id
          in: query
          description: Reference ID of the starting node
          required: false
          schema:
            type: string
        - name: end_ref_id
          in: query
          description: Reference ID of the ending node
          required: false
          schema:
            type: string
      responses:
        '200':
          description: HTML visualization of the shortest path
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-token
security:
  - ApiKeyAuth: []